name: Android Build and Test

on:
  push:
    branches:
      - main # adjust the branch name as needed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run tests
        run: ./gradlew testDebug
